blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration_form'),
    path('profile/<int:pk>/update/', views.MyProfileUpdate.as_view(), name='profile_update'),
    path('posts/', views.PostList.as_view(), name='posts_list'),
    path('post/<int:pk>/create/', views.PostCreate.as_view(), name='post_create_form'),
    path('post/<int:pk>/details', views.PostView.as_view(), name='post_details'),
    path('profile/<int:pk>/info/', views.AuthorDetail.as_view(), name='author_info'),
    path('profile/<int:pk>/my_posts/', views.MyPostsListView.as_view(), name='my_posts'),
    path('profile/<int:pk>/post_update/', views.MyPostUpdate.as_view(), name='post_update'),
    path('post/<int:pk>/all_comments/', views.CommentsList.as_view(), name='comments_list'),
    path('feedback/', views.feedback, name='send_feedback'),
]

core/urls.py
from core import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='blog/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


User = get_user_model()


class Post(models.Model):
    BOOL = (
        (True, 'Publish'),
        (False, 'Draft'),
    )

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    heading = models.CharField(max_length=50, default='No heading')
    text = models.TextField()
    short_definition = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/',
                              blank=True,
                              null=True,
                              default='moon.png',
                              verbose_name='Load Image')
    is_published = models.BooleanField(choices=BOOL, verbose_name='Publish or Draft')
    pub_date = models.DateTimeField('date published', auto_now=True)

    def __str__(self):
        return self.heading


class Comment(models.Model):
    author = models.CharField(max_length=100, verbose_name='username')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField(max_length=400)
    is_published = models.BooleanField(default=False)
    pub_date = models.DateTimeField('date published', blank=True, null=True, auto_now=True)

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm
from django.forms import ModelForm

from .models import Comment, Post, User


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'text']


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['heading', 'short_definition', 'text', 'image', 'is_published']
        widgets = {
            'is_published': forms.RadioSelect
        }


class FeedbackForm(forms.Form):

    GRADES = (
        ('5', 'Five'),
        ('4', 'Four'),
        ('3', 'Three'),
        ('2', 'Two'),
        ('1', 'One'),
    )
    author = forms.CharField(max_length=100, required=True)
    title = forms.CharField(max_length=100, required=True)
    text = forms.CharField(widget=forms.Textarea, required=True)
    evaluate_the_blog = forms.ChoiceField(choices=GRADES, help_text='1 is the lowest score, 5 is the top score')
    reply_me = forms.BooleanField(required=False)


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class PasswordForm(PasswordChangeForm):

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        self.user.save()
        return self.user


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Count
from django.db.models import Prefetch
from django.http import Http404, JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View, generic
from django.views.decorators.cache import cache_page
from django.views.generic import FormView
from django.views.generic.detail import SingleObjectMixin

from .forms import CommentForm, FeedbackForm, PostForm, RegisterForm
from .models import Comment, Post, User
from .tasks import notification_for_admin, send_feedback_to_admin


@cache_page(15)
def index(request):
    users = User.objects.filter(is_staff=False, is_superuser=False).aggregate(Count('id'))
    posts = Post.objects.aggregate(Count('id'))
    comments = Comment.objects.aggregate(Count('id'))
    most_commented_posts = Comment.objects.values('post', 'post__heading').annotate(comments=Count('post')).order_by(
        '-comments')[:5]
    return render(request, 'blog/index.html', {'users': users,
                                               'posts': posts,
                                               'comments': comments,
                                               'most_commented_posts': most_commented_posts})


class UserRegistrationView(SuccessMessageMixin, generic.FormView):
    form_class = RegisterForm
    fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('blog:index')
    success_message = 'Welcome to our blog!!!'

    def form_valid(self, form):
        user = form.save()
        user.save()
        return super().form_valid(form)


class MyProfileUpdate(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'username', 'email']
    template_name = 'blog/my_profile_form.html'
    success_message = 'Your profile info has been successfully saved!!!'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:profile_update', kwargs={'pk': pk})

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class AuthorDetail(generic.DetailView):
    model = User
    fields = ['first_name', 'username', 'last_login']
    template_name = 'blog/author_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_posts'] = Post.objects.filter(author_id=self.kwargs['pk']).aggregate(Count('id'))
        return context


class PostCreate(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Post
    fields = ['heading', 'short_definition', 'text', 'image', 'is_published']
    template_name = 'blog/post_form.html'

    def post(self, request, *args, **kwargs):
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post_form.instance.author = self.request.user
            is_published = post_form.cleaned_data['is_published']
            post_form.instance.is_published = is_published
            new_post = post_form.save()
            new_post.save()
            messages.success(self.request, 'Your post has been successfully created!!!')
            notification_for_admin.delay(notif='post')
            return redirect('blog:posts_list')
        return super().post(request, *args, **kwargs)


class MyPostUpdate(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Post
    fields = ['heading', 'short_definition', 'text', 'image', 'is_published']
    template_name = 'blog/my_post_update_form.html'
    success_url = reverse_lazy('blog:index')
    success_message = 'Your post has been successfully updated!!!'

    def get_object(self, queryset=None):
        post_initial = Post.objects.select_related('author').get(id=self.kwargs['pk'])
        if post_initial.author != self.request.user:
            raise Http404
        return post_initial

    def form_valid(self, post_form):
        post_form.instance.author = self.request.user
        is_published = post_form.cleaned_data['is_published']
        post_form.instance.is_published = is_published
        return super().form_valid(post_form)


class PostDetails(generic.DetailView):
    model = Post
    template_name = 'blog/post_details.html'

    def dispatch(self, request, *args, **kwargs):
        post = Post.objects.get(id=self.kwargs['pk'])
        if not post.is_published:
            messages.warning(self.request, "This post isn't published, or doesn't exist!!!")
            return redirect('blog:index')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Post.objects.select_related('author').prefetch_related(
            Prefetch('comments', Comment.objects.filter(is_published=True).order_by('-pub_date'))
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context


@method_decorator(cache_page(15), name='dispatch')
class PostList(generic.ListView):
    model = Post
    template_name = 'blog/posts_list.html'
    paginate_by = 3

    def get_queryset(self):
        return Post.objects.select_related('author').filter(is_published=True).order_by('-pub_date')


@method_decorator(cache_page(15), name='dispatch')
class MyPostsListView(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = 'blog/my_posts_list.html'
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(author__id=self.request.user.id).order_by('-pub_date')


class CommentFormView(SuccessMessageMixin, SingleObjectMixin, FormView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/post_details.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            text = comment_form.cleaned_data['text']
            author = comment_form.cleaned_data['author']
            new_comment = Comment(text=text, author=author, post_id=kwargs['pk'])
            new_comment.save()
            messages.success(self.request, "Your comment will be added soon!")
            notification_for_admin.delay(notif='comment')
            return redirect('blog:post_details', pk=kwargs['pk'])
        return super().post(request, *args, **kwargs)


class CommentsList(generic.ListView):
    model = Comment
    template_name = 'blog/comments_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Comment.objects.filter(post_id=self.kwargs['pk'], is_published=True).order_by('-pub_date')


class PostView(View):

    def get(self, request, *args, **kwargs):
        view = PostDetails.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentFormView.as_view()
        return view(request, *args, **kwargs)


def feedback(request):
    data = {}
    if request.method == 'POST':
        feedback_form = FeedbackForm(request.POST)
        if feedback_form.is_valid():
            data['form_is_valid'] = True
            author = feedback_form.cleaned_data['author']
            title = feedback_form.cleaned_data['title']
            text = feedback_form.cleaned_data['text']
            reply = feedback_form.cleaned_data['reply_me']
            score = feedback_form.cleaned_data['evaluate_the_blog']
            send_feedback_to_admin.delay(author, title, text, score, reply)
        else:
            data['form_is_valid'] = False
    else:
        feedback_form = FeedbackForm()
    data['html_form'] = render_to_string('blog/send_feedback.html', {'form': feedback_form}, request=request)
    return JsonResponse(data)

templates/blog/author_details.html
{% extends 'blog/base_generic.html' %}

{% block content %}
<div class="wrapper_for_registration_page">
  <div class="update_link">
    <p>Name: {{ user.first_name }}</p>
    <p class="margin_bottom_24">Username: {{ user.username }}</p>
    <p class="margin_bottom_24">Last online: {{ user.last_login }}</p>
    <p>This author has {{ num_posts.id__count }} posts</p>
  </div>
</div>
{% endblock %}

templates/blog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div class="wrapper">
    <header class="header navbar navbar-dark bg-dark">
    <nav>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active"><a class="nav-link" href="{% url 'blog:registration_form' %}">Registration</a></li>
            <li class="nav-item active margin_bottom_24"><a class="nav-link" href="{% url 'login' %}">LogIn</a></li>
            <li class="nav-item active"><a class="nav-link" href="{% url 'blog:index' %}">Main</a></li>
            <li class="nav-item active margin_bottom_24"><a class="nav-link" href="{% url 'blog:posts_list' %}">All Posts</a></li>
            <li class="nav-item active">
                <button type="button" class="feedback_button js-feedback" data-url="{% url 'blog:send_feedback' %}">Send Feedback</button>
            </li>
            <div id="modal-feedback" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        {% include 'blog/send_feedback.html' %}
                    </div>
                </div>
            </div>
            {% if request.user.is_authenticated %}
                <li class="nav-item active"><a class="nav-link" href="{% url 'blog:my_posts' pk=request.user.id %}">My Posts</a></li>
                <li class="nav-item active margin_bottom_24"><a class="nav-link" href="{% url 'blog:post_create_form' pk=request.user.id %}">Create Post</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'blog:profile_update' pk=request.user.id %}">Change my profile</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'logout' %}">LogOut</a></li>
            {% endif %}
        </ul>
    </nav>
  </header>
    <main class="main">
    {% block content %}
    {% endblock %}
    </main>
</div>
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous" defer></script>
<script src="{% static 'js/feedback.js' %}" defer></script>
</body>
</html>

templates/blog/comments_list.html
{% extends "blog/base_generic.html" %}

{% block content %}
    <div class="posts_wrapper">
    {% for comment in object_list %}
        <div class="comment">
            <span><strong>{{ comment.author }}</strong></span>
            <span class="comment_date">{{ comment.pub_date }}</span>
        <p class="margin_bottom_24">
            {{ comment.text }}
        </p>
        </div>
    {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
        </span>
    </div>
{% endblock %}

templates/blog/email_for_user.html
Someone's leaved a comment to your post! Follow the link below:
http://127.0.0.1:8000{% url 'blog:post_details' pk=post_pk %}

templates/blog/index.html
{% extends "blog/base_generic.html" %}

{% block content %}

<div class="wrapper">
<div class="left_column_main_page">
    {% if messages %}
            {% for m in messages %}
            <div class="alert {{ m.tags }} alert-dismissible shadow fade show" role="alert">
             <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                 <span aria-hidden="true">Close</span>
             </button>
                {{ m }}
            </div>
            {% endfor %}
    {% endif %}

    <h1 class="margin_bottom_24"><strong>MyBlog</strong></h1>

    <div class="about_us">
        <h2><strong>About Us</strong></h2>
        <p>Users on site: {{ users.id__count }}</p>
        <p>Number of posts: {{ posts.id__count }}</p>
        <p>Number of comments: {{ comments.id__count }}</p>
    </div>
</div>

<div class="top_posts_column">
    <h2 class="margin_bottom_24"><strong>Top 5 posts</strong></h2>
    {% for single_post in most_commented_posts %}
        <a href="{% url 'blog:post_details' pk=single_post.post %}" class="single_top_post">
            <p class="top_post_title">{{ single_post.post__heading }}</p>
            <span>Number of comments: {{ single_post.comments }} </span>
        </a>
    {% endfor %}
</div>
</div>
{% endblock %}

templates/blog/my_post_update_form.html
{% extends "blog/base_generic.html" %}

{% block content %}
    <div class="wrapper_for_registration_page">
    <form class='form' enctype="multipart/form-data" action="" method="post">
    {% csrf_token %}
        <p class="margin_bottom_24"><strong>Post Update</strong></p>
        {% for fm in form %}
        <table class="register_form">
            {{ fm.label }}
            {{ fm }}
        </table>
        {% endfor %}
        <input type="submit" value="Create" class="margin_bottom_24"/>
   </form>
    </div>
{% endblock %}

templates/blog/my_posts_list.html
{% extends 'blog/base_generic.html' %}

{% block content %}
    <div class="posts_wrapper">
        <p class="margin_bottom_24"><strong>My posts:</strong></p>
            {% for post in object_list %}
                    <a href="{% url 'blog:post_update' pk=post.id %}" class="my_posts">
                        <span class="my_posts_title">{{ post }}</span>
                        {% if post.is_published %}
                            <span class="lable_post published_post">Published</span>
                        {% else %}
                            <span class="lable_post drafted_post">Drafted</span>
                        {% endif %}
                    </a>
            {% empty %}
                <p>No posts yet</p>
            {% endfor %}
    </div>


<div class="pagination">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
        </span>
</div>

{% endblock %}

templates/blog/my_profile_form.html
{% extends "blog/base_generic.html" %}

{% block content %}
    {% if messages %}
            {% for m in messages %}
            <div class="alert {{ m.tags }} alert-dismissible shadow fade show" role="alert">
             <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                 <span aria-hidden="true">Close</span>
             </button>
                {{ m }}
            </div>
            {% endfor %}
    {% endif %}

    <div class="wrapper_for_registration_page">
        <form action="" method="post">
            {% csrf_token %}
            <p class="margin_bottom_24"><strong>Change your profile info</strong></p>
            {% for fm in form %}
                <table class="register_form">
                    {{ fm.label }}
                    {{ fm }}
                </table>
            {% endfor %}
        <input type="submit" value="Change"  class="margin_bottom_24"/>
        </form>

    <a href="{% url 'password_change' %}" class="link_lost_password margin_bottom_24">Change password</a>

    </div>
{% endblock %}

templates/blog/post_details.html
{% extends 'blog/base_generic.html' %}

{% block content %}
{% if messages %}
            {% for m in messages %}
            <div class="alert {{ m.tags }} alert-dismissible shadow fade show" role="alert">
             <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                 <span aria-hidden="true">Close</span>
             </button>
                {{ m }}
            </div>
            {% endfor %}
{% endif %}

<div class="wrapper_for_post_details_page">
        <h2 class="margin_bottom_24">{{ post.heading }}</h2>
        <a class="links_on_details_page" href="{% url 'blog:author_info' pk=post.author.id %}">{{ post.author }}</a>
        <img class="img_for_details" src="{{ post.image.url }}">
        <div class="post_text">
            {{ post.text }}
        </div>

        <span><strong>Leave a comment:</strong></span>
        <form class="comment_input" action="" method="post">
        {% csrf_token %}
            {% for fm in form %}
                <table>
                    {{ fm.label }}
                    {{ fm }}
                </table>
            {% endfor %}
            <input type="submit" value="Submit" />
        </form>


    <div class="comments_section">
        <span><strong>Last comments:</strong></span><br>
        {% for comment in post.comments.all|slice:":10" %}
        <span><strong>{{ comment.author }}</strong></span><br>
        <p class="margin_bottom_24">{{ comment.text }}</p><br>
            {% if not forloop.last %} {% endif %}
            {% empty %}
                <p>No comments yet</p>
        {% endfor %}
    </div>

    <a class="links_on_details_page" href="{% url 'blog:comments_list' pk=post.id %}">Read all comments</a>
</div>

{% endblock %}

templates/blog/post_form.html
{% extends "blog/base_generic.html" %}

{% block content %}
    <div class="wrapper_for_registration_page">
    <form class="form" enctype="multipart/form-data" action="" method="post">
    {% csrf_token %}
        <p class="margin_bottom_24"><strong>Create Post</strong></p>
        {% for fm in form %}
        <table>
            {{ fm.label }}
            {{ fm }}
        </table>
        {% endfor %}
        <input type="submit" value="Create" class="margin_bottom_24"/>
   </form>
    </div>
{% endblock %}

templates/blog/posts_list.html
{% extends "blog/base_generic.html" %}


{% block content %}
    {% if messages %}
            {% for m in messages %}
            <div class="alert {{ m.tags }} alert-dismissible shadow fade show" role="alert">
             <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                 <span aria-hidden="true">Close</span>
             </button>
                {{ m }}
            </div>
            {% endfor %}
    {% endif %}

    <div class="posts_wrapper">
    {% for post in object_list %}
        <section class="post">
            <img src="{{ post.image.url }}" class="img_for_post_list" alt="Post Image">
            <div class="post_info">
                <h2 class="margin_bottom_24">
                    <a href="{% url 'blog:post_details' pk=post.id %}">{{ post.heading }}</a>
                    {% if request.user.id == post.author.id %}
                        <a class="update_link" href="{% url 'blog:post_update' pk=post.id %}">Update</a>
                    {% endif %}
                </h2>
                <div class="author_wrapper">
                    <span class="post_author">
                        <a href="{% url 'blog:author_info' pk=post.author.id %}">{{ post.author }}</a>
                    </span>
                    <span class="post_created_at">
                        {{ post.pub_date }}
                    </span>
                </div>
                <p class="post_short_def">
                    {{ post.short_definition }}
                </p>
            </div>
        </section>
    {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
        </span>
    </div>
{% endblock %}

templates/blog/send_feedback.html
{% block content %}
    <div class="wrapper_for_registration_page">
    <form class="form js-feedback-form" action="{% url 'blog:send_feedback' %}" method="post">
    {% csrf_token %}
        {% for fm in form %}
        <table class="register_form">
            {{ fm.label }}
            {{ fm }}
            {{ fm.help_text }}
        </table>
        {% endfor %}
        <input type="submit" value="Send" class="margin_bottom_24"/>
   </form>
    </div>
{% endblock %}